# Generated by Django 5.2.7 on 2025-10-17 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 20, 11, 0, 49, 393604, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
