# Generated by Django 5.2.7 on 2025-10-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=models.SmallIntegerField(
                choices=[(1, "MEMBER"), (2, "ADMIN"), (3, "MANAGER")], default=1
            ),
        ),
    ]
