# Generated by Django 5.2.7 on 2025-10-18 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_alter_invitation_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 21, 8, 53, 57, 317014, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
