# Generated by Django 5.2.7 on 2025-10-16 07:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_alter_teammember_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="token",
            field=models.CharField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
