# Generated by Django 5.2.7 on 2025-10-16 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0003_alter_invitation_token_alter_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 19, 8, 55, 37, 528178, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
