# Generated by Django 5.2.7 on 2025-10-20 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0003_alter_invitation_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 23, 9, 4, 57, 542923, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
