# Generated by Django 5.2.7 on 2025-11-02 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0004_alter_invitation_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 5, 6, 39, 41, 187143, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
